[patch] Support for CP4D 4.8 in Gitops and ArgoCD
ibm-mas/cli pull request #1008
Opened 2024-06-01 06:08 UTC by caroazad

Add file template and configure CP4D 4.8 to deploy with argoCD. Supporting 4.8.0 and 4.8.1
Changes tested and passed as shown below in this image (image showing a run in argocd for cp4d 4.8.0)

![Screenshot 2024-06-01 at 1 32 04 AM](https://github.com/ibm-mas/cli/assets/28932072/ddcb71d8-ba3f-44a9-93c6-b78459dac3c0)

2024-06-03 09:45 UTC, whitfiea requested changes
How do we set the catalogsource versions in this file: https://github.com/ibm-mas/gitops/blob/poc/instance-applications/080-ibm-cp4d/templates/01-ibm-cp4d_CatalogSources.yaml#L16

2024-06-03 09:45 UTC, whitfiea commented on image/cli/mascli/functions/gitops_cp4d
> +  -r, --region-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}             Region ID
CLUSTER_ID should be REGION_ID

2024-06-03 09:45 UTC, whitfiea commented on image/cli/mascli/functions/gitops_cp4d
> +  export REGION=${REGION:-${SM_AWS_REGION}}
can this be:
```
  export REGION_ID=${REGION_ID:-${SM_AWS_REGION}}
```

2024-06-03 09:45 UTC, whitfiea commented on image/cli/mascli/functions/gitops_cp4d
> +        export REGION=$1 && shift
REGION_ID and --region-id

2024-06-03 09:45 UTC, whitfiea commented on image/cli/mascli/functions/gitops_cp4d
> +  [[ -z "$REGION" ]] && ggitops_cp4d_help "REGION is not set"
should be REGION_ID

2024-06-03 09:45 UTC, whitfiea commented on image/cli/mascli/functions/gitops_cp4d
> +  export CPD_SCALE_CONFIG="medium"
We would want to have these last two configurable:
```
  export CPFS_SIZE="small"
  export CPD_SCALE_CONFIG="medium"
```

So have the defaults but let those be overwritten if are passed in. these would also need to be exposed on the task/pipeline

2024-06-03 11:57 UTC, caroazad commented
> How do we set the catalogsource versions in this file: https://github.com/ibm-mas/gitops/blob/poc/instance-applications/080-ibm-cp4d/templates/01-ibm-cp4d_CatalogSources.yaml#L16

I did not import them because it was only one set and only runs when cp4d version is 4.8.0

2024-06-04 08:51 UTC, whitfiea requested changes

2024-06-04 08:51 UTC, whitfiea commented on tekton/src/pipelines/gitops/gitops-mas-apps.yml.j2
> +      type: string
We should set `default: ""` for these as these would be optional, and we need a default value

2024-06-05 11:30 UTC, whitfiea approved these changes

2024-06-05 11:31 UTC, merged