[patch] MASCORE-3383 Added HMAC to COS role
ibm-mas/cli pull request #1215
Opened 2024-08-28 07:32 UTC by Vishal-patel-7

2024-08-29 11:47 UTC, whitfiea requested changes
The ansible-devops role now allows the config scope to be set and the use_hmac to be set, which is all fine. But that means that for an env that has assist, mvi and manage installed we need the following set:
- objectstorage-cfg at system scope with use_hmac as false
- objectstorage-cfg at app/workspace(for manage) scope with use_hmac as true

I don't think the changes here allow the scope to be set or for more than one config/dependency to be created

2024-08-29 12:02 UTC, Vishal-patel-7 commented
> The ansible-devops role now allows the config scope to be set and the use_hmac to be set, which is all fine. But that means that for an env that has assist, mvi and manage installed we need the following set:
> 
> * objectstorage-cfg at system scope with use_hmac as false
> * objectstorage-cfg at app/workspace(for manage) scope with use_hmac as true
> 
> I don't think the changes here allow the scope to be set or for more than one config/dependency to be created

I don't know how to handle this but the aim for the changes are to give new environment variable support for ansible-devops role. @chiragcsatani can you confirm what we need to do ? This is to fix fvt issue for manage but for assist & mvi we may have to revisit this code and ansible-devops role also.

2024-08-30 07:55 UTC, whitfiea requested changes

2024-08-30 07:55 UTC, whitfiea commented on tekton/src/pipelines/gitops/gitops-mas-deps.yml.j2
> +          value: $(params.use_hmac
missing bracket

2024-08-30 07:57 UTC, Vishal-patel-7 commented on tekton/src/pipelines/gitops/gitops-mas-deps.yml.j2
> +          value: $(params.use_hmac
Corrected..

2024-08-30 07:59 UTC, whitfiea approved these changes

2024-08-30 08:10 UTC, merged