Mongo feature s390x
ibm-mas/cli pull request #1337
Opened 2024-11-11 15:28 UTC by Rajeshri-Shil

Kindly review the changes for mongodb for s390x.

2024-11-11 16:36 UTC, whitfiea requested changes
Can you add a description to the PR and update the title as to what this change is and what it is for, and what testing has happened?

2024-11-11 16:36 UTC, whitfiea commented on python/src/mas/cli/install/params.py
> +    "mongodb_action"
missing a comma

2024-11-11 16:36 UTC, whitfiea commented on python/src/mas/cli/install/argParser.py
> +    const="byo"
Why does it have byo?

2024-11-11 16:36 UTC, whitfiea commented on python/src/mas/cli/install/argBuilder.py
> +        if self.getParam('mongodb_action') == "install" and self.getParam('architecture') != "s390x":
what about uninstall?

2024-11-11 16:36 UTC, whitfiea commented on python/src/mas/cli/install/argBuilder.py
> +        elif self.getParam('mongodb_action') == "byo":
byo isn't an action i recognise https://github.com/ibm-mas/ansible-devops/blob/35017863e41ff139d567671a507800c49b4f1bc5/ibm/mas_devops/roles/mongodb/README.md?plain=1#L48

2024-12-11 16:26 UTC, Rajeshri-Shil commented
closin PR as the above changes does not require now.

2024-12-11 16:26 UTC, closed without merging