[patch] updates to manage task def
ibm-mas/cli pull request #203
Opened 2023-03-10 13:34 UTC by leo-miran

Updates to manage task definition so tasks:
- add param `mas_appws_components` to task so pipeline tasks can verify if they should be executed with current pipeline definition
- Reorder of manage fvt-apps tasks
- Adding new user creation tasks for IS

2023-03-10 15:37 UTC, leo-miran commented
Successful run of this branch. The failed task you see in the image is related to a wrong parameter that was fed into the pipeline.
![image](https://user-images.githubusercontent.com/105313348/224358174-d525b55a-6304-4567-9f49-9627e32e178f.png)

2023-03-10 20:49 UTC, leo-miran commented
Here's a second run where I fixed the parameter causing the issue in the previous comment
![image](https://user-images.githubusercontent.com/105313348/224425397-d136f9a5-39ee-493e-9b5f-0825916ed131.png)
and a close up image
![image](https://user-images.githubusercontent.com/105313348/224425490-fc8e3903-6a3b-45ef-af26-0c24ddb6915c.png)

2023-03-14 09:48 UTC, durera requested changes

2023-03-14 09:48 UTC, durera commented on image/cli/install-ansible/ibm-mas_devops.tar.gz
I can't merge this into master with a custom build of the ansible collection inside it ... is there a PR in the ansible collection that needs to be merged before this can be?

2023-03-14 10:46 UTC, leo-miran commented on image/cli/install-ansible/ibm-mas_devops.tar.gz
No prs for the ansible colletion that I need. I only picked this because I merged the rel/master into this branch in order to get latest updates for for artifactory. This custom build came from those merges.
Should I just delete the tar file?

2023-03-15 11:44 UTC, durera approved these changes

2023-03-15 11:44 UTC, merged