[minor] Support Cloud Pak for Data 4.6.4
ibm-mas/cli pull request #262
Opened 2023-04-26 13:53 UTC by andrercm

2023-05-02 17:00 UTC, whitfiea approved these changes

2023-05-02 17:04 UTC, whitfiea requested changes
Should the ibm-mas_devops.tar.gz be removed?

2023-05-05 09:02 UTC, whitfiea submitted a review, later dismissed
Approving but can you update the PR title as it doesn't seem to be able supporting CPD 4.6.4 but about installing SPSS and Openscale.

2023-05-05 09:06 UTC, whitfiea commented
@andrercm Also you need a changelog entry https://github.com/ibm-mas/cli/blob/master/docs/changes.md. note that 4.1 was missed and needs adding.

2023-05-24 08:34 UTC, durera submitted a review, later dismissed

2023-05-24 08:36 UTC, merged