[minor] add support for aws route53 as dns provider for MAS installs
ibm-mas/cli pull request #308
Opened 2023-05-19 22:18 UTC by andrercm

This PR enables option to configure an existing (it does not create one) AWS route53 hosted zone and configures a custom cluster issuer and corresponding webhook to generate Let's Encrypt well known public certs for MAS.

<img width="296" alt="image" src="https://github.com/ibm-mas/cli/assets/31037381/fae00156-ca1a-4c61-955b-8620283b9fb5">

2023-05-25 09:11 UTC, whitfiea requested changes
Can you add the changelog entry as well?

2023-05-25 09:11 UTC, whitfiea commented on image/cli/mascli/functions/provision_aws
> +  # export IPI_PULL_SECRET_FILE="/opt/app-root/src/masconfig/pull-secret"                   # IPI_PULL_SECRET_FILE
Can we just delete this line?

2023-05-25 19:38 UTC, andrercm commented on image/cli/mascli/functions/provision_aws
> +  # export IPI_PULL_SECRET_FILE="/opt/app-root/src/masconfig/pull-secret"                   # IPI_PULL_SECRET_FILE
Done

2023-05-26 14:58 UTC, whitfiea approved these changes

2023-05-26 15:09 UTC, merged