CIS Compliance for SaaS #12281
ibm-mas/cli pull request #440
Opened 2023-08-25 07:42 UTC by Yolandabjyf

create a new function for  CIS Compliance under cli/image/cli/mascli/functions

2023-08-30 15:30 UTC, whitfiea requested changes

2023-08-30 15:30 UTC, whitfiea commented on image/cli/mascli/functions/gitops_init_cis_compliance
> +        export SECRETS_KEY_SEPERATOR=$1 && shift
I don't think this function needs the secrets related options does it?

2023-08-30 15:30 UTC, whitfiea commented on image/cli/mascli/templates/gitops/cis-compliance.yaml.j2
> +      - CreateNamespace=true
We should set this to false as we don't want it to create namespaces

2023-08-31 02:39 UTC, Yolandabjyf commented on image/cli/mascli/functions/gitops_init_cis_compliance
> +        export SECRETS_KEY_SEPERATOR=$1 && shift
Yes, you are right. I have removed the secret manager part.

2023-08-31 02:40 UTC, Yolandabjyf commented on image/cli/mascli/templates/gitops/cis-compliance.yaml.j2
> +      - CreateNamespace=true
In what situation we don't want it to create namespaces?

2023-08-31 07:49 UTC, whitfiea commented on image/cli/mascli/templates/gitops/cis-compliance.yaml.j2
> +      - CreateNamespace=true
We found a few issues like argocd won't delete the namespace that it created when the CreateNamespace=true is set. Instead we add the namespace resource into the application like this https://github.com/ibm-mas/gitops/blob/poc/applications/ibm-mas-suite/templates/01-ibm-mas_namespace.yaml so it is just another resource.

2023-09-01 14:11 UTC, whitfiea requested changes

2023-09-01 14:11 UTC, whitfiea commented on tekton/src/tasks/gitops/gitops-init-cis-compliance.yaml
> +        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
Can we add the following after this line so we exit if we can't log in. 
```
        OC_RC=$?
        if [ $OC_RC -ne 0 ]; then
          echo "oc login failed"
          exit 1
        fi
```

2023-09-01 14:11 UTC, whitfiea commented on image/cli/mascli/templates/gitops/cis-compliance.yaml.j2
> +    managedNamespaceMetadata:
This `managedNamespaceMetadata` section we need to remove as it was causing issues. That change has come in recently after you did these changes. Just delete lines 25 to 27

2023-09-01 14:11 UTC, whitfiea commented on image/cli/mascli/templates/gitops/cis-compliance.yaml.j2
> +# IBM Cloud Pak Foundational Services
Comment needs fixing

2023-09-01 14:11 UTC, whitfiea commented on image/cli/mascli/functions/gitops_init_cis_compliance
> +        gitops_init_cis_compliance_help
This line needs to add the message so it becomes 
```
gitops_init_cis_compliance_help "Usage Error: Unsupported option \"${key}\" "
```
If we don't do that then the function returns with a rc of 0 and so the task completes ok when it should fail.

2023-09-04 08:47 UTC, whitfiea approved these changes

2023-09-04 08:47 UTC, merged