[minor] Support kafka providers
ibm-mas/cli pull request #451
Opened 2023-08-31 22:26 UTC by andrercm

2023-09-06 09:44 UTC, whitfiea requested changes

2023-09-06 09:44 UTC, whitfiea commented on docs/commands/install.md
> +- `--kafka-provider KAFKA_PROVIDER`                             Required. Set Kafka provider. Supported options are `redhat` (Red Hat AMQ Streams), `strimzi` and `ibm` (IBM Event Streams)
not aws?

2023-09-06 09:44 UTC, whitfiea commented on image/cli/mascli/functions/install
> +      --kafka-provider ${COLOR_YELLOW}KAFKA_PROVIDER${TEXT_RESET}                              Set Kafka provider. Supported options are 'redhat' (Red Hat AMQ Streams), 'strimzi' and 'ibm' (IBM Cloud
or AWS?

2023-09-06 09:44 UTC, whitfiea commented on image/cli/mascli/functions/pipeline_show_config
> +   if [[ "${MAS_APP_CHANNEL_MANAGE}" == '' ]]
I don't think this indent is needed?

2023-09-06 09:44 UTC, whitfiea commented on image/cli/mascli/functions/pipeline_show_config
> +    if [[ "$KAFKA_ACTION_SYSTEM" == "install" && "$KAFKA_PROVIDER" == "aws" ]]; then
indent wrong here?

2023-09-06 16:29 UTC, whitfiea approved these changes

2023-09-12 10:52 UTC, durera approved these changes

2023-09-12 11:19 UTC, merged