[patch] support to delete mirror registry
ibm-mas/cli pull request #460
Opened 2023-09-06 23:12 UTC by caroazad

Add support to delete the mirror registry

2023-09-08 00:00 UTC, caroazad commented
Test was successful. Is there anything we would like to change? Here is a screenshot after the deletion of the registry
<img width="1175" alt="Screenshot 2023-09-07 at 4 02 47 PM" src="https://github.com/ibm-mas/cli/assets/28932072/c3b024c2-d590-4ea8-b165-b79e53ec9ffc">

2023-09-08 09:36 UTC, whitfiea requested changes
Comment on the readme, and need to remove the image/cli/install-ansible/ibm-mas_devops.tar.gz file

2023-09-08 09:36 UTC, whitfiea commented on docs/commands/teardown-registry.md
> +
Can we add some more words to this file. What does it do? Why would you use it? Any impacts of doing this? Will running this cause my MAS system to stop working? Do I have to mirror again?

2023-09-09 06:28 UTC, whitfiea approved these changes

2023-09-09 06:29 UTC, merged