[patch] documentation for the uninstall command
ibm-mas/cli pull request #593
Opened 2023-11-01 16:57 UTC by stonepd

2023-11-02 10:43 UTC, durera requested changes

2023-11-02 10:43 UTC, durera commented on mkdocs.yml
> +      - "upgrade": commands/uninstall.md
Small typo here ...

2023-11-02 11:31 UTC, stonepd commented on mkdocs.yml
> +      - "upgrade": commands/uninstall.md
Thanks, I've corrected it

2023-11-03 13:10 UTC, durera approved these changes

2023-11-03 13:36 UTC, merged