[patch] add must-gather for Optimizer
ibm-mas/cli pull request #815
Opened 2024-03-01 18:50 UTC by andrefgj

2024-03-01 22:33 UTC, alequint requested changes
@andrefgj could you please update PR description with some test evidence indicating the code added worked fine in your tests?

2024-03-04 13:23 UTC, andrefgj commented
> @andrefgj could you please update PR description with some test evidence indicating the code added worked fine in your tests?

Hi @alequint. The test evidence was provided in the description. Just let me know if it is enough, OK?

Thanks!

2024-03-06 14:40 UTC, andrercm approved these changes
LGTM

2024-03-06 16:10 UTC, alequint approved these changes

2024-03-06 16:10 UTC, merged