[patch] UDS/DRO migration storage class fix
ibm-mas/cli pull request #849
Opened 2024-03-20 11:23 UTC by yuvraj-vansure

- [MASCORE-2054](https://jsw.ibm.com/browse/MASCORE-2054): prompt user for storgaclass during uds to dro migration. 
- removed mirror-dro flag from help doc

2024-03-25 16:23 UTC, whitfiea submitted a review, later dismissed

2024-03-28 18:05 UTC, lokesh-sreedhara approved these changes, later dismissed

2024-03-28 18:40 UTC, lokesh-sreedhara approved these changes

2024-04-02 16:46 UTC, lokesh-sreedhara requested changes

2024-04-02 16:46 UTC, lokesh-sreedhara commented on image/cli/mascli/functions/update
> +          if prompt_for_confirm_default_yes "Do you want to use your own storage class to configure DRO?"; then
we need to support Non-interactive install for this prompt as well.

2024-04-02 16:53 UTC, lokesh-sreedhara commented on image/cli/mascli/functions/update
> +          if prompt_for_confirm_default_yes "Do you want to use your own storage class to configure DRO?"; then
use `if [[ "$NO_CONFIRM" != "true" ]];` then like i used here. 

![image](https://github.com/ibm-mas/cli/assets/110647904/cc4e29b3-ecb9-4b79-b335-2652972b889d)

2024-04-05 15:21 UTC, lokesh-sreedhara submitted a review, later dismissed

2024-04-05 15:22 UTC, lokesh-sreedhara commented
cam someone help review/approve this PR for merge?

2024-04-05 15:48 UTC, andrercm commented
@yuvraj-vansure have you tested if this works as expected for both interactive/non-interactive aproaches and also including `--no-confirm` argument?

2024-04-05 16:43 UTC, lokesh-sreedhara commented
> @yuvraj-vansure @lokesh-sreedhara have you tested if this works as expected for both interactive/non-interactive aproaches and also including `--no-confirm` argument?

@andrercm ohh i did not check `--no-confirm`. @yuvraj-vansure can u help with this? when `mas update --no-confirm` is run, it should overide all user prompts, make sure DRO_STORAGE_CLASS takes default value "" on `--no-confirm`

2024-04-05 22:26 UTC, lokesh-sreedhara approved these changes, later dismissed

2024-04-08 19:47 UTC, andrercm approved these changes
This will be approved to be merged due time constraints, but adjustments will be implemented so that code follows same standard as other implementations in the MAS CLI.

I had a review session with Lokesh and Yuvraj and we identified some enhancements to be done:

- Add logic in `update` pipeline to skip `uds` task based on `UDS_ACTION` valid values, instead of adding `skip` action into ansible-devops role... If a task must be skipped, it should be proactively skipped in the pipeline instead of being skipped in the role execution.
- Fix the logic on how the DRO_STORAGE_CLASS is determined so it follows same standards as the other places where we define the storage classes. Use https://github.com/ibm-mas/cli/blob/master/image/cli/mascli/functions/internal/install_config_storage_classes as example.

2024-04-08 19:47 UTC, andrercm commented on image/cli/install-ansible/ibm-mas_devops.tar.gz
We should remove this tar.gz

2024-04-08 19:47 UTC, andrercm commented on build/bin/build-tekton.sh
> +  VERSION=${VERSION:-18.17.3-pre.MASCORE-2241}
Is this needed?

2024-04-08 19:52 UTC, merged