[minor] support option to --skip-grafana-install
ibm-mas/cli pull request #950
Opened 2024-05-10 16:44 UTC by sanjayprab

This PR adds the argument `--skip-grafana-install` that allows skipping grafana  but avoiding to check if Grafana is available in the cluster based on the available of the operator package. and sets `CLUSTER_MONITORING_INCLUDE_GRAFANA=False`

This has been implemented in:

mas install

2024-05-10 16:59 UTC, andrercm requested changes
added some thoughts to it

2024-05-10 16:59 UTC, andrercm commented on image/cli/mascli/functions/install
> +        SKIP_GRAFANA_INSTALL=true
what if we do:
```
--skip-grafana-install)
CLUSTER_MONITORING_INCLUDE_GRAFANA=false
```

2024-05-10 16:59 UTC, andrercm commented on image/cli/mascli/functions/install
> +  if [[ "$SKIP_GRAFANA_INSTALL" == "true" ]]; then
and then here we just do a check to see if `CLUSTER_MONITORING_INCLUDE_GRAFANA` is defined already, if not defined then we set it upon packagemanigest logic
```
# if CLUSTER_MONITORING_INCLUDE_GRAFANA is not defined 
if [[ -z "$CLUSTER_MONITORING_INCLUDE_GRAFANA" ]]; then
```

2024-05-10 17:25 UTC, sanjayprab commented on image/cli/mascli/functions/install
> +        SKIP_GRAFANA_INSTALL=true
used it

2024-05-12 08:20 UTC, durera requested changes
I have overhauled cluster_monitoring / grafana in the pending major update .. can you take a look at how to integrate this with that branch (the cluster_monitoring stage isn't even in the pipeline anymore, there's a dedicated grafana stage).

I think the action is to work with the GRAFANA_ACTION env var in the update, and ensure it can be set explicitly instead of only being able to be set automatically.

2024-05-13 12:11 UTC, sanjayprab commented
@durera closing this PR and have created a new PR  with a new branch  due to various conflicts.

2024-05-13 12:11 UTC, closed without merging