[minor] [MASCORE-1896] Allow db2ucluster addons and auditlogs PV to be set
ibm-mas/cli pull request #991
Opened 2024-05-24 19:51 UTC by twhart

Added and tested out the new configuration on noble3 in our SaaS fyre environment. This allows us to configure the storage class and size for the audit logs in our db2u configuration

<img width="1366" alt="image" src="https://github.com/ibm-mas/cli/assets/13783927/c5ef6875-38f1-4ac7-b661-6c232fc1eeeb">

2024-05-28 14:48 UTC, whitfiea requested changes

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/help/install_help
> +      --db2u-audit-logs-storage ${COLOR_YELLOW}DB2_AUDIT_LOGS_STORAGE_SIZE${TEXT_RESET}   Customize Db2 storage capacity
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on docs/commands/install.md
> +- `--db2u-audit-logs-storage DB2_AUDIT_LOGS_STORAGE_SIZE`   Customize Db2 storage capacity
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/install
> +        export DB2_AUDIT_LOGS_STORAGE_SIZE=$1 && shift
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/install_config_db2
> +    echo_reset_dim " - Audit Logs:       ${COLOR_MAGENTA}${DB2_AUDIT_LOGS_STORAGE_SIZE:-Default}"
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/install_config_sno
> +    export DB2_AUDIT_LOGS_STORAGE_ACCESSMODE=ReadWriteOnce
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/install_config_storage_classes
> +# - db2_audit_logs_storage_class [ibmc-block-gold, ocs-storagecluster-ceph-rbd, managed-premium]
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/install_config_storage_classes_sno
> +# - db2_audit_logs_storage_class [ibmc-block-gold, ocs-storagecluster-ceph-rbd, managed-premium]
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/install_pipelinerun_preview
> +    echo_reset_dim "Transaction Audit Logs Storage .. ${COLOR_MAGENTA}${DB2_AUDIT_LOGS_STORAGE_SIZE:-<default>}"
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/internal/save_config
> +export DB2_AUDIT_LOGS_STORAGE_SIZE=$DB2_AUDIT_LOGS_STORAGE_SIZE
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/templates/pipelinerun-install.yaml
> +      value: '$DB2_AUDIT_LOGS_STORAGE_ACCESSMODE'
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on tekton/src/params/install-db2.yml.j2
> +  description: Storage capacity (audit logs)
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on tekton/src/pipelines/taskdefs/dependencies/db2.yml.j2
> +      value: $(params.storage_class_rwo)
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on tekton/src/tasks/dependencies/db2.yml.j2
> +      default: ""
This file isn't used in gitops so we should remove this change

2024-05-28 14:48 UTC, whitfiea commented on image/cli/mascli/functions/gitops_db2u_database
> +    export DB2_AUDIT_LOGS_STORAGE_ACCESSMODE=ReadWriteOnce
According to https://ibmdocs-test.dcs.ibm.com/docs/en/SSQNUZ_4.6_test?topic=security-configuring-audit-logging this should be ReadWriteMany

2024-05-28 20:40 UTC, twhart commented
Tested out the audit config addon changes 

ReadWriteMany Change:
<img width="1316" alt="image" src="https://github.com/ibm-mas/cli/assets/13783927/ef538675-4028-4d5b-971c-92c352e8ff23">

Build Configurations:
<img width="1116" alt="image" src="https://github.com/ibm-mas/cli/assets/13783927/902cd862-23fb-472f-a695-0fdfa9c6d91e">

<img width="1334" alt="image" src="https://github.com/ibm-mas/cli/assets/13783927/fbaa7c45-64e5-472f-bd7d-4870ea4d3c43">


Build 
https://cloud.ibm.com/devops/pipelines/tekton/8bb11078-2a03-43b2-9d30-df3ea17af143/runs/df8ef5f0-2a59-4d1e-8eb7-30d04c541c48/gitops-db2u-database-manage/gitops-db2u-database?env_id=ibm:yp:us-south

2024-05-29 07:06 UTC, whitfiea requested changes

2024-05-29 07:06 UTC, whitfiea commented on docs/commands/install.md
> +- `--db2u-temp-storage DB2_TEMP_STORAGE_SIZE`               Customize Db2 storage capacity
This file change should be removed as well.

2024-05-29 07:06 UTC, whitfiea commented on image/cli/mascli/functions/gitops_db2u_database
> +      --db2-addons-audit-config-yaml ${COLOR_YELLOW}DB2_ADDONS_AUDIT_CONFIG_YAML${TEXT_RESET}
Looks like we lost the descrioption for these two

2024-05-29 07:06 UTC, whitfiea commented on image/cli/mascli/functions/gitops_db2u_database
> +  [[ -z "$DB2_AUDIT_LOGS_STORAGE_CLASS" ]] && gitops_db2u_help "DB2_AUDIT_LOGS_STORAGE_CLASS is not set"
The audit logs are optional so we shouldn't have DB2_AUDIT_LOGS_STORAGE_CLASS as a requirement

2024-05-29 07:06 UTC, whitfiea commented on image/cli/mascli/functions/help/install_help
> +      --db2u-temp-storage ${COLOR_YELLOW}DB2_TEMP_STORAGE_SIZE${TEXT_RESET}               Customize Db2 storage capacity
We should remove this file change as it is not part of gitops

2024-05-30 09:25 UTC, whitfiea requested changes
Can you remove the ibm-mas_devops.tar.gz from this PR as I don't believe it is needed

2024-05-30 09:32 UTC, whitfiea commented
I updated the devops tar.gz to be the gitops one

2024-05-30 09:32 UTC, whitfiea approved these changes

2024-05-30 09:32 UTC, merged